"""
The Flask-SecurityTxt extension.
"""
import re
from copy import deepcopy
from importlib.metadata import version, PackageNotFoundError
from typing import Callable, Optional, Any

from flask import Flask, Response, current_app
from pgpy.errors import PGPDecryptionError

try:
    from pgpy import PGPKey, PGPMessage
except ImportError:
    PGPKey = PGPMessage = None

from flask_security_txt.field_value import (
    get_contact_field_value,
    get_expires_field_value,
    get_encryption_field_value,
    get_acknowledgments_field_value,
    get_preferred_languages_field_value,
    get_canonical_field_value,
    get_policy_field_value,
    get_hiring_field_value)
from flask_security_txt.lib import FieldValue, Field, FlaskSecurityTxtConfig

_DEFAULT_HEADER = """
GENERATED BY FLASK-SECURITYTXT {version}

Flask-SecurityTxt has been developed by M.P. van de Weerd for
Parcifal Programmatics under the AGPLv3 licence.

https://pypi.org/project/Flask-SecurityTxt/
https://scm.parcifal.dev/parcifal/flask-security-txt

https://www.van-de-weerd.net/
https://www.parcifal.dev/

"""

_FIELD_CASE_DECORATORS = {
    "standard": lambda x: x,
    "lower": lambda x: x.lower(),
    "upper": lambda x: x.upper(),
}

# the keys of this dict also determine which config keys can be specified
# through the config parameter of the security txt class
_DEFAULT_CONFIG = {
    "endpoint": "security_txt",
    "contact": None,
    "contact_mailbox": "security",
    "expires": None,
    "expires_offset": {"weeks": 1},
    "encryption": None,
    "acknowledgments": None,
    "preferred_languages": None,
    "canonical": None,
    "policy": None,
    "hiring": None,
    "file_name": "security.txt",
    "sign_key": None,
    "header": _DEFAULT_HEADER,
    "footer": None,
    "field_case": "standard",
    "comment_line_prefix": "# "
}


def _normalize_config_key(key: str) -> str:
    """
    Normalize a config key by replacing non-alphanumeric characters with
    underscores and converting to uppercase.
    """
    return re.sub(r"[^A-Z0-9_]", "_", key.upper())


def _render_field(key: str, value: FieldValue,
                  field_case_decorator: Callable[[str], str]) -> Field:
    """
    Render a field section of the security.txt file as a list containing all
    lines of the field. A field can actually consist of multiple lines, all
    starting with the same key, in case the value is a list, tuple, etc.
    """
    if not value:
        return []

    if isinstance(value, str):
        value = (value,)

    return [f"{field_case_decorator(key)}: {v}" for v in value]


def _render_comment_field(comment: str) -> Field:
    """
    Format a comment string by adding the comment line prefix to each line.
    """
    comment_line_prefix = current_app.config.get(
        "SECURITY_TXT_COMMENT_LINE_PREFIX")
    ll = []
    for cl in comment.splitlines():
        l = comment_line_prefix + cl
        ll.append(l.rstrip())
    return ll


def _render_doc_field(section: str) -> Field:
    """
    Render a section of the security.txt file.
    """
    key = f"SECURITY_TXT_{section.upper()}"
    value = current_app.config.get(key)

    if value is not None and not isinstance(value, str):
        raise ValueError(f"{key} must be None or a string")

    if not value:
        return []

    try:
        v = version("Flask-SecurityTxt")
    except PackageNotFoundError:
        # might happen in dev envs
        v = "?.?.?"

    return _render_comment_field(value.replace("{version}", v))


def _render_header_field() -> Field:
    """
    Render the header section of the security.txt file.
    """
    return _render_doc_field("header")


def _render_footer_field() -> Field:
    """
    Render the footer section of the security.txt file.
    """
    return _render_doc_field("footer")


def _render_annotation_field(key: str) -> Field:
    """
    Render a comment section of the security.txt file.
    """
    comment_key = f"SECURITY_TXT_{_normalize_config_key(key)}_COMMENT"

    if comment_key not in current_app.config:
        return []

    comment = current_app.config.get(comment_key)

    if comment is None:
        return []
    if not isinstance(comment, str):
        raise TypeError(f"{comment_key} must be a string")

    # comments are preceded by an empty line
    return [""] + _render_comment_field(comment)


def _send_security_txt():
    """
    @return:
        The full security.txt as an HTTP response.
    """
    lines = []

    field_case = current_app.config.get("SECURITY_TXT_FIELD_CASE")

    if field_case not in _FIELD_CASE_DECORATORS:
        raise ValueError(f"Unknown field case \"{field_case}\"")

    field_case_decorator = _FIELD_CASE_DECORATORS[field_case]
    lines.extend(_render_header_field())

    fields = {
        "Contact": get_contact_field_value(),
        "Expires": get_expires_field_value(),
        "Encryption": get_encryption_field_value(),
        "Acknowledgments": get_acknowledgments_field_value(),
        "Preferred-Languages": get_preferred_languages_field_value(),
        "Canonical": get_canonical_field_value(),
        "Policy": get_policy_field_value(),
        "Hiring": get_hiring_field_value()
    }

    for key, value in fields.items():
        if field := _render_field(key, value, field_case_decorator):
            lines.extend(_render_annotation_field(key))
            lines.extend(field)

    lines.extend(_render_footer_field())
    body = "\n".join(lines) + "\n"

    if PGPKey and PGPMessage and (sign_key := current_app.extensions["security_txt"]["sign_key"]):
        message = PGPMessage.new(body, cleartext=True)

        if sign_key.is_protected:
            sign_key_passphrase = current_app.config.get("SECURITY_TXT_SIGN_KEY_PASSPHRASE")

            if sign_key_passphrase is None:
                raise RuntimeError("SECURITY_TXT_SIGN_KEY_PASSPHRASE must be "
                                   "set if SECURITY_TXT_SIGN_KEY is protected")

            with sign_key.unlock(sign_key_passphrase):
                message |= sign_key.sign(message)
        else:
            message |= sign_key.sign(message)

        body = str(message)

    return Response(body, content_type="text/plain; charset=utf-8")


# pylint: disable=too-few-public-methods
class SecurityTxt:
    """
    Extends Flask application with a dynamically generated security.txt.
    """

    # pylint: disable=too-many-arguments, too-many-positional-arguments
    def __init__(self, app: Optional[Flask] = None,
                 config: FlaskSecurityTxtConfig = None):
        self.defaults = deepcopy(_DEFAULT_CONFIG)

        if config is not None:
            invalids = []

            for key in config:
                if key in self.defaults:
                    continue
                invalids.append(key)

            if len(invalids) > 0:
                raise ValueError(f"invalid configuration keys: {invalids}")

            self.defaults.update(config)

        if app is not None:
            self.init_app(app)

    def init_app(self, app: Flask):
        """
        Initialize the specified Flask application to generate a security.txt.
        """

        def _types_or_fail(k: str, tt: tuple[Any, ...]):
            v = app.config.get(k)
            if None in tt:
                tt = (e if e is not None else type(None) for e in tt)
            tt = tuple(tt)
            if isinstance(v, tt):
                return
            raise TypeError(f"config key {k} has value {v}, but must "
                            f"have type {' or '.join([t.__name__ for t in tt])}")

        for key, value in self.defaults.items():
            app.config.setdefault(
                _normalize_config_key(f"SECURITY_TXT_{key}"), value)

        app.config.setdefault("WELL_KNOWN_DIR", ".well-known")

        for key in ("WELL_KNOWN_DIR",
                    "SECURITY_TXT_FILE_NAME",
                    "SECURITY_TXT_ENDPOINT",
                    "SECURITY_TXT_SIGN_KEY"):
            _types_or_fail(key, (str, None))

        sign_key_path = app.config.get("SECURITY_TXT_SIGN_KEY")
        sign_key = None

        if sign_key_path is not None:
            sign_key, _ = PGPKey.from_file(sign_key_path)

            if sign_key.is_public:
                raise RuntimeError(
                    "SECURITY_TXT_SIGN_KEY must be a private key")

            if sign_key.is_protected:
                sign_key_passphrase = current_app.config.get("SECURITY_TXT_SIGN_KEY_PASSPHRASE")

                if sign_key_passphrase is None:
                    raise RuntimeError("SECURITY_TXT_SIGN_KEY_PASSPHRASE must "
                                       "be set if SECURITY_TXT_SIGN_KEY is "
                                       "protected")

                # unlock the key once, just to make sure
                # the passphrase is correct
                try:
                    with sign_key.unlock(sign_key_passphrase):
                        pass
                except PGPDecryptionError as e:
                    raise RuntimeError("SECURITY_TXT_SIGN_KEY_PASSPHRASE is "
                                       "incorrect") from e

        if not hasattr(app, "extensions"):
            app.extensions = {}

        app.extensions["security_txt"] = {
            "instance": self,
            "sign_key": sign_key
        }

        well_known_dir = app.config.get("WELL_KNOWN_DIR")
        file_name = app.config.get("SECURITY_TXT_FILE_NAME")
        endpoint = app.config.get("SECURITY_TXT_ENDPOINT")

        rule = ""

        if well_known_dir := well_known_dir.strip("/"):
            rule += f"/{well_known_dir}"
        if file_name := file_name.strip("/"):
            rule += f"/{file_name}"
        if not rule:
            rule = "/"

        app.add_url_rule(rule, endpoint, _send_security_txt)
