"""
The Flask-SecurityTxt extension.
"""
import os

from datetime import datetime as dt, timedelta as td, timezone as tz
from dateutil import parser
from importlib.metadata import version
from typing import Any, Generator, Union, Optional
from urllib.parse import urlsplit

from dateutil.parser import ParserError
from flask import Flask, Response, request, url_for
from flask_babel import get_babel
from pgpy import PGPKey, PGPMessage
from werkzeug.routing import BuildError

_DEFAULT_HEADER = None

_DEFAULT_FOOTER = """
#
# GENERATED BY FLASK-SECURITYTXT {version}
#
# Flask-SecurityTxt has been developed by M.P. van de Weerd for
# Parcifal Programmatics under the GPLv3 licence.
#
# https://pypi.org/project/Flask-SecurityTxt/
# https://git.parcifal.dev/parcifal/flask-security-txt
#
# https://www.van-de-weerd.net/
# https://www.parcifal.dev/
#
"""

_TYPE_OPTIONAL_STRINGS = Union[None, str, list[str], tuple[str]]

_FIELD_CASE_DECORATORS = {
    "standard": lambda x: x,
    "lower": lambda x: x.lower(),
    "upper": lambda x: x.upper(),
}


# pylint: disable=too-few-public-methods, too-many-instance-attributes
class SecurityTxt:
    """
    Extends Flask application with a dynamically generated security.txt.
    """

    # pylint: disable=too-many-arguments, too-many-positional-arguments
    def __init__(self, app: Optional[Flask] = None,
                 default_endpoint: str = "security_txt",
                 default_contact_mailbox: str = "security",
                 default_expires_offset: tuple = (0, 0, 0, 0, 0, 0, 1),
                 default_preferred_languages: Union[list[str], tuple[str]] = ("en", ),
                 default_canonical: Optional[str] = None,
                 default_dir: str = ".well-known",
                 default_file_name: str = "security.txt",
                 default_sign_key: Optional[str] = None,
                 default_header: Optional[str] = _DEFAULT_HEADER,
                 default_footer: Optional[str] = _DEFAULT_FOOTER,
                 default_field_case: str = "standard"):
        self._default_endpoint = default_endpoint
        self._default_contact_mailbox = default_contact_mailbox
        self._default_expires_offset = default_expires_offset
        self._default_preferred_languages = default_preferred_languages
        self._default_canonical = default_canonical
        self._default_dir = default_dir
        self._default_file_name = default_file_name
        self._default_sign_key = default_sign_key
        self._default_header = default_header
        self._default_footer = default_footer
        self._default_field_case = default_field_case

        # to be set by init_app()
        self.app = None
        self.sign_key = None

        if app is not None:
            self.init_app(app)

    def init_app(self, app: Flask):
        """
        Initialize the specified Flask application to generate a security.txt.
        """
        self.app = app

        if not hasattr(app, "extensions"):
            app.extensions = {}

        app.extensions["security_txt"] = self

        app.config.setdefault("SECURITY_TXT_ENDPOINT",
                              self._default_endpoint)
        app.config.setdefault("SECURITY_TXT_CONTACT_MAILBOX",
                              self._default_contact_mailbox)
        app.config.setdefault("SECURITY_TXT_EXPIRES_OFFSET",
                              self._default_expires_offset)
        app.config.setdefault("SECURITY_TXT_CANONICAL",
                              self._default_canonical)
        app.config.setdefault("SECURITY_TXT_HEADER",
                              self._default_header)
        app.config.setdefault("SECURITY_TXT_FOOTER",
                              self._default_footer)
        app.config.setdefault("SECURITY_TXT_FIELD_CASE",
                              self._default_field_case)

        well_known_dir = app.config.get("WELL_KNOWN_DIR",
                                        self._default_dir)
        name = app.config.get("SECURITY_TXT_FILE_NAME",
                              self._default_file_name)

        app.add_url_rule(f"/{well_known_dir}/{name}",
                         app.config.get("SECURITY_TXT_ENDPOINT"),
                         self._send_security_txt)

        sign_key = app.config.get("SECURITY_TXT_SIGN_KEY",
                                  self._default_sign_key)

        if sign_key is not None:
            self.sign_key, _ = PGPKey.from_file(sign_key)

    def _send_security_txt(self):
        """
        @return:
            The full security.txt as an HTTP response.
        """
        lines = []
        header = self.app.config.get("SECURITY_TXT_HEADER")

        field_case = self.app.config.get("SECURITY_TXT_FIELD_CASE")

        if field_case not in _FIELD_CASE_DECORATORS:
            raise ValueError(f"Unknown field case \"{field_case}\"")

        field_case_decorator = _FIELD_CASE_DECORATORS[field_case]

        if header is not None:
            if not isinstance(header, str):
                raise ValueError("SECURITY_TXT_HEADER must be None or a "
                                 "string.")
            lines.append(header.format(version=version("Flask-SecurityTxt")))

        for key, item in self._get_fields().items():
            if isinstance(item, Generator):
                item = list(item)

            if item is None or len(item) == 0:
                continue

            comment_key = f"SECURITY_TXT_{key.upper()}_COMMENT"

            if comment_key in self.app.config:
                comment = self.app.config.get(comment_key)
                lines.append(comment)

            if not isinstance(item, (list, tuple)):
                item = (item, )

            for value in item:
                if not isinstance(value, str):
                    raise ValueError(f"SECURITY_TXT_{key.upper()} must be "
                                     f"None, a string, or a list or tuple of "
                                     f"strings.")

                lines.append(f"{field_case_decorator(key)}: {value}")

        footer = self.app.config.get("SECURITY_TXT_FOOTER")

        if footer is not None:
            if not isinstance(footer, str):
                raise ValueError("SECURITY_TXT_FOOTER must be None or "
                                 "a string.")
            lines.append(footer.format(version=version("Flask-SecurityTxt")))

        body = "\n".join(lines)

        if self.sign_key is not None:
            assert isinstance(self.sign_key, PGPKey)

            message = PGPMessage.new(body, cleartext=True)
            message |= self.sign_key.sign(message)

            body = str(message)

        return Response(body, mimetype="text/plain")

    def _get_fields(self) -> dict:
        """
        @return:
            A dict mapping the keys to the values of the security.txt fields.
        """
        return {
            "Contact": self._get_field_value_contact(),
            "Expires": self._get_field_value_expires(),
            "Encryption": self._get_field_value_encryption(),
            "Acknowledgments": self._get_field_value_acknowledgments(),
            "Preferred-Languages": self._get_field_value_preferred_languages(),
            "Canonical": self._get_field_value_canonical(),
            "Policy": self._get_field_value_policy(),
            "Hiring": self._get_field_value_hiring()
        }

    def _get_urls_from_value(self,
                             value: _TYPE_OPTIONAL_STRINGS,
                             schemes: _TYPE_OPTIONAL_STRINGS=None):
        """
        Parse zero or more URLs from the specified config value. The URLs can
        be defined as either a full URL string starting with one of the
        specified schemes or as an end-point that can be resolved by the
        Flask application.
        """
        if value is None or len(value) == 0:
            return
        if schemes is None:
            schemes = ["https"]

        if not isinstance(value, (list, tuple)):
            value = (value, )

        for scheme in schemes:
            if isinstance(scheme, str):
                continue
            raise ValueError("Scheme must be None, a string, or a list or "
                             "tuple of strings.")

        for item in value:
            if not isinstance(item, str):
                raise ValueError(f"URL must be None, a string, or a list or "
                                 f"tuple of strings.")

            url = urlsplit(item)

            if url.scheme in schemes:
                yield item
                continue

            if self.app.has_static_folder and os.path.exists(
                    os.path.join(str(self.app.static_folder), item)):
                yield url_for("static",
                              filename=item,
                              _external=True,
                              _scheme="https")
                continue

            try:
                yield url_for(item, _external=True, _scheme="https")
            except BuildError as error:
                raise ValueError(
                    "A URL field value must either be string starting with "
                    "https://, the name of a static file or an end-point "
                    "name that can be resolved by the flask application."
                ) from error

    def _get_field_value_contact(self) -> Generator[str, Any, None]:
        """
        @return:
            The value of the contact field.
        """
        value = self.app.config.get("SECURITY_TXT_CONTACT")

        if value is None:
            mailbox = self.app.config.get("SECURITY_TXT_CONTACT_MAILBOX")
            if not isinstance(mailbox, str):
                raise ValueError("SECURITY_TXT_CONTACT_MAILBOX must be "
                                 "a string")
            domain = request.host.rsplit(":", 1)[0]
            yield f"mailto:{mailbox}@{domain}"
            return

        try:
            yield from self._get_urls_from_value(value, [
                "https", "mailto", "tel"])
        except ValueError as error:
            raise ValueError(
                "SECURITY_TXT_CONTACT is misconfigured.") from error

    def _get_field_value_expires(self) -> str:
        """
        @return:
            The value of the expires field.
        """
        value = self.app.config.get("SECURITY_TXT_EXPIRES")

        if isinstance(value, str):
            try:
                value = parser.parse(value)
            except ParserError:
                raise ValueError("SECURITY_TXT_EXPIRES string must use a"
                                 "valid datetime format.")
        if isinstance(value, dt):
            return value.replace(microsecond=0).isoformat()

        if value is not None:
            raise ValueError("SECURITY_TXT_EXPIRES must be None, a string, "
                             "or a datetime.")

        offset = self.app.config.get("SECURITY_TXT_EXPIRES_OFFSET")

        if not isinstance(offset, (td, tuple)):
            raise ValueError("SECURITY_TXT_EXPIRES_OFFSET must be a timedelta "
                             "or tuple.")

        if isinstance(offset, tuple):
            offset = td(*offset)

        value = dt.now(tz.utc) + offset
        return value.replace(microsecond=0).isoformat()

    def _get_field_value_encryption(self):
        """
        @return:
            The value of the encryption field.
        """
        try:
            yield from self._get_urls_from_value(
                self.app.config.get("SECURITY_TXT_ENCRYPTION"), [
                    "https", "dns", "openpgp4fpr"])
        except ValueError as error:
            raise ValueError(
                "SECURITY_TXT_ENCRYPTION is misconfigured.") from error

    def _get_field_value_acknowledgments(self):
        """
        @return:
            The value of the acknowledgments field.
        """
        try:
            yield from self._get_urls_from_value(
                self.app.config.get("SECURITY_TXT_ACKNOWLEDGEMENTS"))
        except ValueError as error:
            raise ValueError(
                "SECURITY_TXT_ACKNOWLEDGMENTS is misconfigured.") from error

    def _get_field_value_preferred_languages(self):
        """
        @return:
            The value of the preferred languages field.
        """
        value = self.app.config.get("SECURITY_TXT_PREFERRED_LANGUAGES")

        if isinstance(value, str):
            return value
        if isinstance(value, (list, tuple)):
            return ", ".join(value)

        # fall back to babel if it is loaded, otherwise use default
        if "babel" in self.app.extensions:
            babel = get_babel()
            return ", ".join([
                t.language
                for t in getattr(babel.instance, "list_translations")()
            ])

        return ", ".join(self._default_preferred_languages or [])

    def _get_field_value_canonical(self):
        """
        @return:
            The value of the canonical field.
        """
        try:
            yield from self._get_urls_from_value(
                self.app.config.get("SECURITY_TXT_CANONICAL",
                                    self.app.config.get("SECURITY_TXT_ENDPOINT")))
        except ValueError as error:
            raise ValueError(
                "SECURITY_TXT_CANONICAL is misconfigured.") from error

    def _get_field_value_policy(self):
        """
        @return:
            The value of the policy field.
        """
        try:
            yield from self._get_urls_from_value(
                self.app.config.get("SECURITY_TXT_POLICY"))
        except ValueError as error:
            raise ValueError(
                "SECURITY_TXT_POLICY is misconfigured.") from error

    def _get_field_value_hiring(self):
        """
        @return:
            The value of the hiring field.
        """
        try:
            yield from self._get_urls_from_value(
                self.app.config.get("SECURITY_TXT_HIRING"))
        except ValueError as error:
            raise ValueError(
                "SECURITY_TXT_HIRING is misconfigured.") from error
